### ISSUE TITLE
import/using HDF fails: HDF5-DIAG: Error detected in HDF5 (1.10.0)

### ISSUE THREAD

**Issue by anowacki** [JuliaLang/HDF5.jl#298]
First of all, apologies that I don't have time to look into this more myself before submitting.

Attempting to use HDF with Julia 0.4.5, on OS X 10.10.5, using HDF5 (both installed via MacPorts), gives an error when trying to `using` or `import` it.  The relevant part of the output is:

```
INFO: Recompiling stale cache file /Users/nowacki/.julia/lib/v0.4/HDF5.ji for module HDF5.
INFO: Recompiling stale cache file /Users/nowacki/.julia/lib/v0.4/Blosc.ji for module Blosc.
HDF5-DIAG: Error detected in HDF5 (1.10.0) thread 0:
  #000: H5P.c line 254 in H5Pcreate(): not a property list class
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0) thread 0:
  #000: H5Pstrcpl.c line 171 in H5Pset_char_encoding(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: H5Pint.c line 3817 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: H5Pint.c line 3767 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
ERROR: InitError: Error setting char encoding
 in h5p_set_char_encoding at /Users/nowacki/.julia/v0.4/HDF5/src/plain.jl:1951
 in __init__ at /Users/nowacki/.julia/v0.4/HDF5/src/plain.jl:2320
 in _require_from_serialized at ./loading.jl:84
 in _require_from_serialized at /opt/local/lib/julia/sys.dylib
 in require at /opt/local/lib/julia/sys.dylib
 in process_options at /opt/local/lib/julia/sys.dylib
 in _start at /opt/local/lib/julia/sys.dylib
during initialization of module HDF5
```

See the [full log](https://github.com/JuliaLang/HDF5.jl/files/236450/HDF_add.txt), including versioninfo() from the command:
```bash
$ rm -rf ~/.julia/v0.4; julia --check-bounds=yes -e "versioninfo(); Pkg.update(); Pkg.add(\"HDF5\"); using HDF5"
```
This does work with 0.5.0-dev+2440, however (despite all the warnings).

Please do let me know what I can do to help diagnose the problem, and thanks for the hard work on HDF5 support.

---
Edit: Incorrect logfile uploaded.

**Comment by eschnett** [comment]
You need to use the development version of the HDF5 package to be able to use version 1.10. You'd use the command `Pkg.checkout("HDF5")` to switch.

**Comment by timholy** [comment]
Should we tag a new release?

**Comment by eschnett** [comment]
If you're confident that the recent changes are uncontroversial, then yes. Maybe a minor release to indicate the new feature?

**Comment by timholy** [comment]
You'd be a better judge than me about that. Anything in particular you're concerned about?

**Comment by anowacki** [comment]
> You need to use the development version of the HDF5 package to be able to use version 1.10.

Okay, thanks a lot for pointing that out.  It seems this arose from updating my MacPorts version of HDF5, which I hadn't appreciated had occurred.  I'll look forward to the next release.

**Comment by juliohm** [comment]
I am having the same issue, will a tag be added?

**Comment by vchuravy** [comment]
Archlinux updated to HDF5 1.10 so I also just run into this issue

**Comment by timholy** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5104
